name = "Player Modifier PCx"
uid = "fplayx27-v003-55b4-92b6-64398e7ge43f"
version = 1
copyright = "MIT License"
description = "Specify AIx type modifiers for human players"
author = "maudlin27"
url = ""
icon = "/mods/SpawnACU/ACUIcon.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
