---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 26/10/2022 22:38
---

bModifiersPresent = false --True if want to consider applying
tiBuildRateModByIndex = {}
tiResourceModByIndex = {}

function IsTableEmpty(tTable, bEmptyIfNonTableWithValue)
    --Returns true if a table is empty
    --bEmptyIfNonTableWithValue - Optional, defaults to true; i.e. table treated as empty if non-table

    if (type(tTable) == "table") then
        if next (tTable) == nil then return true
        else
            for i1, v1 in pairs(tTable) do
                if IsTableEmpty(v1, false) == false then return false end
            end
            return true
        end
    else
        if tTable == nil then return true
        else
            if bEmptyIfNonTableWithValue == nil then return true
            else return bEmptyIfNonTableWithValue
            end
        end

    end
end


function OnCreate(oUnit, bIgnoreMapSetup)
    --LOG('OnCreate pre M28InGamecheck, M28Utilities.bM28AIInGame='..tostring(M28Utilities.bM28AIInGame))
    if bModifiersPresent then
        --Is this a valid unit?
        if oUnit.UnitId and not(oUnit.Dead) and oUnit.GetAIBrain then
            --Have we already run this?
            --Do we have a build rate or resource modifier for this unit?
            local oBP = oUnit:GetBlueprint()
            if oBP.Economy.BuildRate or oBP.Economy.ProductionPerSecondMass or oBP.Economy.ProductionPerSecondEnergy then
                --Have we run this before?
                if not(oUnit['PCxCr']) then
                    oUnit['PCxCr'] = true

                end
            end
        end
    end
end