---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 23/08/2025 07:27
---
local PCxMain = import('/mods/Player-Modifier-PCx/lua/Main.lua')
PCxAIBrainClass = AIBrain
PCxBrain = Class(BaseAIBrainClass) {
    OnCreateHuman = function(self, planName)
        ForkThread(PCxMain.OnCreateHuman, self, planName)
        PCxAIBrainClass.OnCreateHuman(self, planName)
    end,
}