---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 23/08/2025 07:27
---

--[[PCxAIBrainClass = AIBrain
PCxBrain = Class(BaseAIBrainClass) {
    OnCreateHuman = function(self, planName)
        PCxAIBrainClass.OnCreateHuman(self, planName)
        import('/mods/PlayerModifierPCx/lua/Main.lua').OnCreateHuman(self, planName)
    end,
}--]]