---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 23/08/2025 08:04
---
local PCxMain = import('/mods/PlayerModifierPCx/lua/Main.lua')
--Needed for LOUD as for some reason callbacks dont trigger for Seraphim (e.g. when building a shield); although expected to be fixed in LOUD, want to leave in in case steam has the same issue
local PCxOldUnit = SConstructionUnit
if PCxOldUnit then
    SConstructionUnit = Class(PCxOldUnit) {
        OnCreate = function(self)
            PCxOldUnit.OnCreate(self)
            if PCxOldUnit.OnCreate then ForkThread(PCxMain.OnCreate, self) end
        end,
    }
end