---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 23/08/2025 07:32
---
--Put anything we want to only run once (not once per aiBrain) below
local PCxBeginSession = BeginSession
local PCxMain = import('/mods/Player-Modifier-PCx/lua/Main.lua')
function BeginSession()
    PCxBeginSession()
    PCxMain.RecordCheatModifiersByIndex()
end