---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 23/08/2025 08:06
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 02/12/2022 09:13
---
local PCxMain = import('/mods/PlayerModifierPCx/lua/Main.lua')

local PCxOldUnit = Unit
if PCxOldUnit then
    Unit = Class(PCxOldUnit) {
        OnCreate = function(self)
            PCxOldUnit.OnCreate(self)
            if PCxOldUnit.OnCreate then ForkThread(PCxMain.OnCreate, self) end
        end,
    }
end